package cmpe273.fandango.exception;

public enum ErrorCode {
	
	ERR_ACCESS_DENIED,
	ERR_INVALID_JSON,
	ERR_IO_EXCEPTION,
	ERR_INTERNAL_SERVER_ERROR,
	ERR_BAD_REQUEST,
	ERR_KEYGEN_BY_SECRET,
	ERR_FILE_NOT_FOUND,
	ERR_ENCRYPTION, 
	ERR_DECRYPTION, 
	ERR_INTEGRITY_VIOLATION
}
